CONFIG_NO_OPTIMIZATIONS=y

CONFIG_GNU_C_EXTENSIONS=y

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_ASSERT=n

CONFIG_BT_CLASSIC=y
CONFIG_BT_AVDTP=y
CONFIG_BT_RFCOMM=y

CONFIG_BT_L2CAP_SEG_RECV=y

CONFIG_BT_SMP=y
CONFIG_BT_L2CAP_DYNAMIC_CHANNEL=y
CONFIG_BT_L2CAP_ECRED=y

CONFIG_ZCBOR=y
CONFIG_MCUMGR=y

CONFIG_BT_A2DP=y
CONFIG_BT_A2DP_SINK=y

CONFIG_BT_MESH=y
CONFIG_SETTINGS=y
CONFIG_BT_SETTINGS=y

CONFIG_BT_MESH_CDB=y
CONFIG_BT_MESH_PROVISIONER=y
CONFIG_BT_MESH_RPR_CLI=y

CONFIG_NETWORKING=y
CONFIG_MQTT_SN_LIB=y
CONFIG_NET_L2_ETHERNET=n

CONFIG_BT_AUDIO=y
CONFIG_BT_BAP_BROADCAST_ASSISTANT=y
CONFIG_BT_BAP_SCAN_DELEGATOR=y

CONFIG_BT_OTS=y

CONFIG_BT_ATT_TX_COUNT=20
CONFIG_BT_TBS_CLIENT_TBS=y
CONFIG_UTF8=y

CONFIG_BT_BAP_UNICAST_CLIENT=y

CONFIG_BT_PER_ADV=y
CONFIG_BT_PER_ADV_RSP=y
CONFIG_BT_BROADCASTER=y

CONFIG_BT_OBSERVER=y
CONFIG_BT_ECC=y
CONFIG_BT_PER_ADV_SYNC=y
# CONFIG_BT_ISO_UNICAST=y
CONFIG_BT_ISO_PERIPHERAL=y
CONFIG_BT_ISO_BROADCASTER=y
CONFIG_BT_ISO_SYNC_RECEIVER=y
CONFIG_BT_DF=y
CONFIG_BT_DF_CONNECTIONLESS_CTE_RX=y
CONFIG_BT_DF_CONNECTION_CTE_RX=y
CONFIG_BT_DF_CONNECTION_CTE_REQ=y
CONFIG_BT_TRANSMIT_POWER_CONTROL=y
# CONFIG_BT_PATH_LOSS_MONITORING=y
CONFIG_BT_PER_ADV_SYNC_RSP=y
CONFIG_BT_PER_ADV_RSP=y
CONFIG_BT_OBSERVER=y
# New features
CONFIG_BT_PER_ADV_SYNC_TRANSFER_SENDER=y
CONFIG_BT_PER_ADV_SYNC_TRANSFER_RECEIVER=y

CONFIG_BT_HFP_HF=y

CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y
CONFIG_NET_IPV4_HDR_OPTIONS=y
CONFIG_NET_6LO=y

CONFIG_NET_SHELL=y

CONFIG_EC_HOST_CMD=y
CONFIG_EC_HOST_CMD_BACKEND_SIMULATOR=y

CONFIG_MCUMGR_MGMT_NOTIFICATION_HOOKS=y

CONFIG_NET_TCP=y

CONFIG_CAN=y
CONFIG_ISOTP=y

#CONFIG_HAS_SEMTECH_RADIO_DRIVERS=y
#CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_LORA=y

# LoRaWAN application layer
CONFIG_LORAWAN=y
CONFIG_LORAMAC_REGION_EU868=y
CONFIG_LORAWAN_NVM_SETTINGS=y

# LoRaWAN services required for FUOTA
CONFIG_LORAWAN_SERVICES=y
CONFIG_HAS_SEMTECH_LORAMAC=y

CONFIG_LORAWAN_APP_CLOCK_SYNC=y
CONFIG_LORAWAN_REMOTE_MULTICAST=y

CONFIG_LORAWAN_FRAG_TRANSPORT=y
CONFIG_LORAWAN_APP_CLOCK_SYNC=y

CONFIG_COAP=y

CONFIG_IPC_SERVICE=y
CONFIG_MBOX=y

CONFIG_BT_BAP_BROADCAST_SOURCE=y
CONFIG_BT_BAP_BROADCAST_SINK=y

CONFIG_BT_ASCS=y
CONFIG_BT_BAP_UNICAST_SERVER=y
CONFIG_BT_ATT_PREPARE_COUNT=3

CONFIG_BT_SHELL=n
CONFIG_BT_A2DP_SOURCE=y
CONFIG_BT_A2DP_SINK=y

CONFIG_BT_HAS_CLIENT=y
CONFIG_BT_HAS=y
CONFIG_BT_HAS_FEATURES_NOTIFIABLE=y

CONFIG_BT_GATT_READ_MULT_VAR_LEN=y
CONFIG_BT_MESH_CFG_CLI=y

CONFIG_BT_MESH_OP_AGG_SRV=y
CONFIG_BT_MESH_OP_AGG_CLI=y

CONFIG_BT_OTS_CLIENT=y